### ISSUE TITLE
package.json repository configuration

### ISSUE THREAD

**Issue by MythicManiac** [LeagueSandbox/LobbyServer#1]
Does the repository configuration on `package.json` support the ssh format? If yes, I think it should be changed to that.

**Comment by chutch1122** [comment]
Here's the documentation for the repository section of node's package.json file: https://docs.npmjs.com/files/package.json#repository

It doesn't say anything about there being an ssh option available.

**Comment by MythicManiac** [comment]
Judging by https://github.com/npm/npm/issues/3521 it looks like it's possible. Should be tested

**Comment by chutch1122** [comment]
Yeah, agreed. I'll push that change with my next commit
